### ISSUE TITLE
Tweak readme

### ISSUE THREAD

**Issue by jdalton** [AVVS/lodash-mixins#1]
`lodash-node` is deprecated in favor of `lodash` or `lodash-compat` as they support cherry-picking, like `require('lodash/object/keys')`.

Also you should use [_.runInContext](https://lodash.com/docs#runInContext) in the example:

``` js
var _ = require('lodash').runInContext();
_.mixin(...);
```

**Comment by AVVS** [comment]
Thx, will update

**Comment by jdalton** [comment]
Awesome!
